### ISSUE TITLE
PrettyFormatStrategy prints chunks non tread-safe, causes mixture in log

### ISSUE THREAD

**Issue by flocsy** [orhanobut/logger#191]
Please try to fill all questions below before submitting an issue.

- Android studio version: 3.1.2
- Android gradle plugin version: 3.1.1
- Logger version: 2.2.0
- Emulator/phone information: OnePlus 3T
- If possible, please add how did you initialize Logger?

```
public class DebugBehaviour extends Timber.Tree{
    public DebugBehaviour(){
        super();
        FormatStrategy formatStrategy = PrettyFormatStrategy.newBuilder()
                .methodCount(99)
                .methodOffset(99)
                .showThreadInfo(false)
                .tag("")
                .build();
        Logger.addLogAdapter(new AndroidLogAdapter(formatStrategy));
    }

    @Override
    protected void log(int priority, @Nullable String tag, @NonNull String message, @Nullable Throwable t) {
        Logger.log(priority, tag, message, t);
    }
}

```

- Is it flaky or does it happen all the time?
All the time

My AndroidStudio's logcat is set up to display log levels in different colors, so it's very esy to see the problem. Basically what happens is that multiple threads log with different log level, and because of PrettyFormatStrategy.log is calling logChunk multiple times but non-syncronized, it causes different threads' log to mix up.

An example:

05-23 00:57:26.419 23965-24152/com.chegg W/System.err:     at com.facebook.stetho.server.LocalSocketServer.bindToSocket(LocalSocketServer.java:142)
    │ GET http://my.example.com/path/to/my.json
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
05-23 00:57:26.419 23965-24152/com.chegg W/System.err:     at com.facebook.stetho.server.LocalSocketServer.listenOnAddress(LocalSocketServer.java:78)
        at com.facebook.stetho.server.LocalSocketServer.run(LocalSocketServer.java:74)
        at com.facebook.stetho.server.ServerManager$1.run(ServerManager.java:40)
05-23 00:57:26.419 23965-24152/com.chegg E/stetho: Could not start Stetho server: main
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ submitted request:
    │ GET http://my.example.com/path/to/my.json
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

So what happens is this:
1. W/System.err: sets the log level to WARN
2. GET http://my.example.com/path/to/my.json is supposed to be DEBUG
3. E/stetho: sets the level to ERROR
4. submitted request: (continuation of 2., should be DEBUG) is now in log level ERROR

**Comment by kosiara** [comment]
I also observed this behaviour. During debugging of PrettyFormatStrategy everything seems to work fine but on app-runtime logs get mixed up. Lines do not match and sometimes there is no logcat header:

i.e. log prints out:
SAMPLE LOG

instead of :
09-04 17:29:52.212 14455-14455/com.sample I/AA_LOG: SAMPLE LOG

```
09-04 17:29:52.212 14455-14455/com.sample I/AA_LOG: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ BLA BLA 1111111111
09-04 17:29:52.213 14455-14455/com.sample I/AA_LOG: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by kosiara** [comment]
Temporary solution would be to buffer the result:

```
import android.util.Log
import com.orhanobut.logger.LogcatLogStrategy

/**
 * Prints log to logcat
 *
 * HINT: This class is redundant and can be removed as soon as issue
 * https://github.com/orhanobut/logger/issues/191
 *
 * is resolved
 *
 * @version 9/4/18
 * @author Bartosz Kosarzycki
 */
public class McLogcatLogStrategy : LogcatLogStrategy() {

    val DEFAULT_TAG = "NO_TAG"
    val START_PREFIX = "┌───" 
    val END_PREFIX = "└──────" 

    override fun log(priority: Int, tag: String?, message: String)
            = logInternal(priority, tag ?: DEFAULT_TAG, message)

    var logContent = ""
    private fun logInternal(priority: Int, tag: String, message: String) {
        when {
            message.startsWith(START_PREFIX) -> {
                logContent = ""
                logContent += ": \n$message"
            }
            message.startsWith(END_PREFIX) -> {
                logContent += "\n" + message
                Log.println(priority, tag, logContent)
            }
            else ->
                logContent += "\n" + message
        }
    }
}
```
