### ISSUE TITLE
代码貌似现在不能运行了

### ISSUE THREAD

**Issue by NortonAhu** [orhanobut/logger#63]
大神，我刚好想下载你的代码学习下RxJava 但是发现已经运行不起来了：
` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.malin.rengwuxianrxjava, PID: 15271
                                                                            java.lang.VerifyError: com/malin/rengwuxianrxjava/activity/MainActivity$AjcClosure1
                                                                                at com.malin.rengwuxianrxjava.activity.MainActivity.rxJavaSolveMiZhiSuoJinAndNestedLoopAndCallbackHell(MainActivity.java:334)
                                                                                at com.malin.rengwuxianrxjava.activity.MainActivity.onCreate(MainActivity.java:133)
                                                                                at android.app.Activity.performCreate(Activity.java:5303)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:142)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5217)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                                                at dalvik.system.NativeStart.main(Native Method)`

**Comment by ZhaoKaiQiang** [comment]
哥们，你跑偏了吧，RxJava怎么跑到Logger这里来了

**Comment by NortonAhu** [comment]
额，怎么会发到这里来了，我错了
