### ISSUE TITLE
java.lang.NoClassDefFoundError: com.orhanobut.logger.LoggerPrinter

### ISSUE THREAD

**Issue by githubityu** [orhanobut/logger#71]
java.lang.NoClassDefFoundError: com.orhanobut.logger.LoggerPrinter
                                                                 at com.orhanobut.logger.Logger.<clinit>(Logger.java:11)
                                                                 at com.llkj.youban.MyApplication.onCreate(MyApplication.java:26)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4394)
                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:141)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1273)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by orhanobut** [comment]
On which version you got this issue?
